server:
  port: 8085
spring:
  application:
    name: oss-service
  cloud:
    nacos:
      server-addr: 124.223.175.150:8848

logging:
  level:
    root: info
    com:
      example: debug
    org:
      springframework:
        r2dbc: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'

oss:
  endPoint: oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI5tFMdUrkP8zpHh5NcGQB
  accessKeySecret: FJjOBonpziQuTvJYdm4yeeROTx3Rxv
  bucketName: fresh-platform-img
